<?php

use Drupal\Core\Extension\Extension;

/**
 * Implements hook_theme_suggestions_HOOK_alter() to conditionally suggest JSX templates.
 */
function demo_jsx_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $temp=[] ;

  foreach ($suggestions as $suggestion) {
    if($suggestion == 'block__search_form_block'){
      $temp[] = $variables['elements'];
    }
    if($suggestion == 'block__search'){
      $variables['elements'] = $temp;
    }
  }
}
/**
 * Implements hook_system_info_alter().
 */
function demo_jsx_system_info_alter(array &$info, Extension $file, $type): void {
  if ($type === 'theme') {
    $info['engine'] = 'jsx';
  }
//  else{
//    print_r($type);
//  }
}
