<?php

use Drupal\Core\Extension\Extension;

/**
 * Implements hook_system_info_alter().
 */
function demo_jsx_system_info_alter(array &$info, Extension $file, $type): void {
  if ($type === 'theme') {
    $info['engine'] = 'jsx';
  }
}


///**
// * Implements hook_theme().
// */
//function demo_jsx_theme() {
//  // This hook is for loading the new templates we define in the module
//  // not for overriding.
//  // refer:-https://www.drupal.org/forum/support/module-development-and-code-questions/2015-06-03/drupal-8-override-template-with#comment-11572031
//  return [
//    'container__demo_jsx' => [
//      'variables' => ['content' => NULL],
//      'template' => 'container',
//      'base hook' => 'form_element',
//      'path' => \Drupal::service('extension.list.module')->getPath('demo_jsx') . '/templates',
//    ],
//  ];
//}


/**
 * Implements hook_theme_registry_alter
 */
function demo_jsx_theme_registry_alter(&$theme_registry) {
  $current_path = \Drupal::service('path.current')->getPath();
  if ($current_path == '/react-component') {
    // If the path is react-component then only load the template-info.json file
    // else it will load the container.twig file
    $theme_registry['container']['path'] = \Drupal::service('extension.list.module')->getPath('demo_jsx') . '/templates/container';
  }
  else{
    $theme_registry['container']['path'] = \Drupal::service('extension.list.module')->getPath('demo_jsx') . '/templates';
  }
}
